item {
  id: 1
  name: 'Beetroot'
}

item {
  id: 2
  name: 'Bell Pepper'
}

item {
  id: 3
  name: 'Bhindi Masala'
}

item {
  id: 4
  name: 'Black Beans'
}

item {
  id: 5
  name: 'Brinjal'
}

item {
  id: 6
  name: 'Broccoli'
}

item {
  id: 7
  name: 'Burgers'
}

item {
  id: 8
  name: 'Butter Chicken'
}

item {
  id: 9
  name: 'Cabbage'
}

item {
  id: 10
  name: 'Carrot'
}

item {
  id: 11
  name: 'Cauliflower'
}

item {
  id: 12
  name: 'Chana Masala'
}

item {
  id: 13
  name: 'Chapati'
}

item {
  id: 14
  name: 'Chicken'
}

item {
  id: 15
  name: 'Chickpeas'
}

item {
  id: 16
  name: 'Cucumber'
}

item {
  id: 17
  name: 'Dahi Vada'
}

item {
  id: 18
  name: 'Dal Makhani'
}

item {
  id: 19
  name: 'Fish'
}

item {
  id: 20
  name: 'French Beans'
}

item {
  id: 21
  name: 'Fruit Salad'
}

item {
  id: 22
  name: 'Kiwi'
}

item {
  id: 23
  name: 'Grapes'
}

item {
  id: 24
  name: 'Fruits'
}

item {
  id: 25
  name: 'Green Dal Moong'
}

item {
  id: 26
  name: 'Green Salad'
}

item {
  id: 27
  name: 'Idli Sambar'
}

item {
  id: 28
  name: 'Masala Dosa'
}

item {
  id: 29
  name: 'Matar Paneer'
}

item {
  id: 30
  name: 'Meat'
}

item {
  id: 31
  name: 'Rice'
}

item {
  id: 32
  name: 'Punjabi Paratha'
}

item {
  id: 33
  name: 'Misal Pav'
}

item {
  id: 34
  name: 'Onion Uttapam'
}

item {
  id: 35
  name: 'Onion'
}

item {
  id: 36
  name: 'Tomato'
}

item {
  id: 37
  name: 'Panner'
}

item {
  id: 38
  name: 'French Fries'
}

item {
  id: 39
  name: 'Pizza'
}

item {
  id: 40
  name: 'French fries'
}

item {
  id: 41
  name: 'Noodles'
}

item {
  id: 42
  name: 'Pasta'
}

item {
  id: 43
  name: 'Sizzler'
}

item {
  id: 44
  name: 'Potato'
}

item {
  id: 45
  name: 'Poha'
}

item {
  id: 46
  name: 'Prawns'
}

item {
  id: 47
  name: 'Lemon'
}

item {
  id: 48
  name: 'Gralic'
}

item {
  id: 49
  name: 'Pumpkin'
}

item {
  id: 50
  name: 'Pumpkin cake'
}

item {
  id: 51
  name: 'Pumpkin seed'
}

item {
  id: 52
  name: 'Qats'
}

item {
  id: 53
  name: 'Quinoa'
}

item {
  id: 54
  name: 'Vegetables'
}

item {
  id: 55
  name: 'Quinoa Soup'
}

item {
  id: 56
  name: 'Spinach'
}

item {
  id: 57
  name: 'Rajma'
}

item {
  id: 58
  name: 'Cake'
}

item {
  id: 59
  name: 'Sabudana'
}

item {
  id: 60
  name: 'Soyabeans'
}

item {
  id: 61
  name: 'Soya chunks'
}

item {
  id: 62
  name: 'Egg'
}

item {
  id: 63
  name: 'Sprouts'
}

item {
  id: 64
  name: 'Kadala'
}

item {
  id: 65
  name: 'Upma'
}

item {
  id: 66
  name: 'Yogurt'
}

item {
  id: 67
  name: 'Idli'
}

item {
  id: 68
  name: 'Vada Pav'
}

item {
  id: 69
  name: 'Samosa'
}

item {
  id: 70
  name: 'Vegetable Soup'
}

item {
  id: 71
  name: 'Vegetable'
}

item {
  id: 72
  name: 'Garlic'
}

item {
  id: 73
  name: 'Yellow Dal'
}

item {
  id: 74
  name: 'Grape'
}

